# Generated by Django 4.1 on 2022-10-08 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Баланс счета')),
                ('title', models.CharField(db_index=True, max_length=60, verbose_name='Наименование счета')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Cчёты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AccountsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='Наименование типа счётов')),
            ],
            options={
                'verbose_name': 'Тип cчётов',
                'verbose_name_plural': 'Типы счётов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Наименование валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Наименование')),
                ('file', models.CharField(db_index=True, max_length=50, verbose_name='Наименование файла')),
                ('unicode', models.CharField(db_index=True, max_length=50, verbose_name='юникод символа')),
                ('unicode_icons', models.CharField(db_index=True, max_length=50, verbose_name='дешифрованный юникод символа')),
            ],
            options={
                'verbose_name': 'иконка',
                'verbose_name_plural': 'иконки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TransactionsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_type', models.BooleanField(verbose_name='Тип:')),
                ('category', models.CharField(db_index=True, max_length=60, verbose_name='Категория')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.currency', verbose_name='Валюта транзакции')),
                ('icons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.icons', verbose_name='Иконка')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец типа')),
            ],
            options={
                'verbose_name': 'Тип транзакций',
                'verbose_name_plural': 'Типы транзакций',
                'ordering': ['main_type'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_value', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Денежная сумма')),
                ('comment', models.TextField(max_length=150, verbose_name='Примечание к транзакции')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата совершения транзакции')),
                ('accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.accounts', verbose_name='Счёт транзакции')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец транзакции')),
                ('transactions_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.transactionstype', verbose_name='Тип транзакции')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-data_time'],
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='accounts_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.accountstype', verbose_name='Тип счёта'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.currency', verbose_name='Валюта счёта'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец счёта'),
        ),
    ]
