# Generated by Django 4.1 on 2022-10-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='comment',
            field=models.TextField(blank=True, max_length=150, verbose_name='Примечание к транзакции'),
        ),
    ]
