# Generated by Django 4.1 on 2022-08-25 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactions_accounts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='currency_id',
            field=models.ForeignKey(limit_choices_to={'owner_id': models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец транзакции')}, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.currency', verbose_name='Валюта транзакции'),
        ),
    ]
