# Generated by Django 4.1 on 2022-08-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transactions_accounts_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='accounts_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.accounts', verbose_name='Счёт транзакции'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transactions_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.transactionstype', verbose_name='Тип транзакции'),
        ),
    ]
