# Generated by Django 4.1 on 2022-09-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_transactionstype_main_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstype',
            name='main_type',
            field=models.BooleanField(verbose_name='Доход/Расход'),
        ),
    ]
