# Generated by Django 4.1 on 2022-09-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstype',
            name='icons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.icons', verbose_name='Иконка'),
        ),
    ]
