# Generated by Django 4.1 on 2022-08-25 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=60, verbose_name='Наименование счета')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Cчёты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AccountsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='Наименование типа счётов')),
            ],
            options={
                'verbose_name': 'Тип cчётов',
                'verbose_name_plural': 'Типов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=10, verbose_name='Наименование валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TransactionsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_type', models.CharField(db_index=True, max_length=60, verbose_name='Главный тип')),
                ('category', models.CharField(db_index=True, max_length=60, verbose_name='Категория')),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.accounts', verbose_name='Валюта транзакции')),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец типа')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_value', models.PositiveBigIntegerField(verbose_name='Денежная сумма')),
                ('comment', models.TextField(verbose_name='Примечание к транзакции')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата совершения транзакции')),
                ('currency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.currency', verbose_name='Валюта транзакции')),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец транзакции')),
                ('transactions_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.transactionstype', verbose_name='Тип транзакции')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-data_time'],
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='accounts_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.accountstype', verbose_name='Тип счёта'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='currency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.currency', verbose_name='Валюта счёта'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец счёта'),
        ),
    ]
