# Generated by Django 4.1 on 2022-08-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionstype',
            options={'ordering': ['main_type'], 'verbose_name': 'Тип транзакций', 'verbose_name_plural': 'Типы транзакций'},
        ),
        migrations.AlterField(
            model_name='transactionstype',
            name='main_type',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Главный тип'),
        ),
    ]
