# Generated by Django 4.1 on 2022-08-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactionstype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Наименование валюты'),
        ),
    ]
