# Generated by Django 4.1 on 2022-08-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_currency_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountstype',
            options={'ordering': ['title'], 'verbose_name': 'Тип cчётов', 'verbose_name_plural': 'Типы счётов'},
        ),
        migrations.RemoveField(
            model_name='transactionstype',
            name='account_id',
        ),
        migrations.AddField(
            model_name='transactionstype',
            name='currency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.currency', verbose_name='Валюта транзакции'),
        ),
    ]
