# Generated by Django 4.1 on 2022-08-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transactions_accounts_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='accounts_type_id',
            new_name='accounts_type',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='currency_id',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='accounts_id',
            new_name='accounts',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='currency_id',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transactions_type_id',
            new_name='transactions_type',
        ),
        migrations.RenameField(
            model_name='transactionstype',
            old_name='currency_id',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='transactionstype',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
