# Generated by Django 4.1 on 2022-09-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_transactionstype_icons_alter_transactions_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Наименование')),
                ('address', models.CharField(db_index=True, max_length=50, verbose_name='Наименование файла')),
            ],
            options={
                'verbose_name': 'иконка',
                'verbose_name_plural': 'иконки',
                'ordering': ['title'],
            },
        ),
    ]
