# Generated by Django 4.1 on 2022-09-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_alter_transactionstype_icons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icons',
            old_name='address',
            new_name='file',
        ),
        migrations.AddField(
            model_name='icons',
            name='unicode',
            field=models.CharField(db_index=True, default='qwerty', max_length=50, verbose_name='юникод символа'),
            preserve_default=False,
        ),
    ]
