# Generated by Django 4.1 on 2022-09-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_icons_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='icons',
            name='unicode_icons',
            field=models.CharField(db_index=True, default='hui', max_length=50, verbose_name='дешифрованный юникод символа'),
            preserve_default=False,
        ),
    ]
