# Generated by Django 4.1 on 2022-09-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_icons_unicode_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='balans',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Баланс счета'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='money_value',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Денежная сумма'),
        ),
        migrations.AlterField(
            model_name='transactionstype',
            name='main_type',
            field=models.BooleanField(verbose_name='Тип:'),
        ),
    ]
